# Generated by Django 3.1.7 on 2021-03-22 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotterpattern',
            name='pattern_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotterpattern_pattern', to='api.pattern'),
        ),
        migrations.AlterField(
            model_name='plotterpattern',
            name='plotter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotterpattern_plotter', to='api.plotter'),
        ),
        migrations.CreateModel(
            name='ParentUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_perms', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
    ]
