# Generated by Django 3.1.7 on 2021-03-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210322_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_user', 'Can view user'),)},
        ),
    ]
