# Generated by Django 3.1.7 on 2021-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210322_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='allowed_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
