# Generated by Django 3.1.7 on 2021-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210323_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='whole_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
