# Generated by Django 3.1.7 on 2021-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plotter_whole_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotterpattern',
            name='stats',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
